### ISSUE TITLE
直近のイベントが一列に表示されない

### ISSUE THREAD

**Issue by sKawashima** [YngLab/Msite#108]
まだ修正されてないよな？

**Comment by ShumpeiKano** [comment]
俺の環境だと1080〜1440pxのうちだと崩れないよ？

**Comment by sKawashima** [comment]
以前に見せやんかったっけ
僕の環境1680では崩れる
もっと言えば1560を超えると崩れる

**Comment by sKawashima** [comment]
横幅の計算式はどういう計算式？
マージンは固定値やけどどういう計算式？

**Comment by sKawashima** [comment]
ある一定以上の横幅を超えるとそれ以上全体の横幅が広がらない仕様だったと思うけど、JSで横幅を指定している以上CSSを破綻させる（!importantを使用する）以外に対処法は無いんやが

**Comment by ShumpeiKano** [comment]
jsで制御しました
