### ISSUE TITLE
ページ全体の縦幅指定がゴミ

### ISSUE THREAD

**Issue by Yakan-Kettle** [YngLab/Msite#28]
せめてスクロールしないことがわかりきってるページぐらいはやりましょう、俺。

**Comment by Yakan-Kettle** [comment]
やりました。
・「アコーディオンが折りたたまれているときはページ縦幅が足りているが、展開するとスクロールが必要になる」という特殊なページへの対応
上記のパターンに対しては現在調整中です（クソオンゲ運営並感

**Comment by sKawashima** [comment]
縦幅指定しやなあかん理由は？

**Comment by Yakan-Kettle** [comment]
普通にコーディングするとフッターが上に寄ってしまうので、スクロールできないほど小さいページの場合、下にガッツリ余白ができてしまうのがキモいからです。

**Comment by Yakan-Kettle** [comment]
しかし、よくある「フッターが常についてくる」というウェブデザインは担当者曰く「やだ。」らしいので。

**Comment by sKawashima** [comment]
絶対値指定はしてないよな？
min-heightとcalc使ってるやら言うこと無いが

**Comment by Yakan-Kettle** [comment]
絶対値はやってないです。

**Comment by Yakan-Kettle** [comment]
calcで指定してます。

**Comment by sKawashima** [comment]
把握

**Comment by Yakan-Kettle** [comment]
ただ、calcに代入している値は、不要な部分のpxを測った値ですのでヘッダーやフッターのデザインが変わると現状ほぼ総書き換えになる問題がありますね

**Comment by Yakan-Kettle** [comment]
ヘッダー・フッターはもともと絶対値なので、計算式自体に問題はありませんが。

**Comment by sKawashima** [comment]
固定値はscss変数に置いてくれると保持性が上がって嬉しいかな

**Comment by Yakan-Kettle** [comment]
min-height使えばアコーディオンの問題にも対応できそうな感じですかね？

**Comment by sKawashima** [comment]
できるかもしれん。検証頼む（バイト休憩終わり

**Comment by Yakan-Kettle** [comment]
ういす

**Comment by Yakan-Kettle** [comment]
min-heightの件ですが、バッチリ行きました。神。

**Comment by Yakan-Kettle** [comment]
あとはアコーディオンの展開幅を自動取得できればPerfectですね

**Comment by Yakan-Kettle** [comment]
もちろんアニメーションを殺さず。
