### ISSUE TITLE
ウィンドウ幅が一定値以下になったときに起こっちゃうレイアウト崩れへの対処

### ISSUE THREAD

**Issue by Yakan-Kettle** [YngLab/Msite#30]
ウィンドウ幅が1440px以上のとき、コンテンツを中央揃えにしてそれ以上サイズを大きくしない
アコーディオンが、ウィンドウ幅を縮めるとlayoutがガバガバになる問題の修正
ヘッダーのアクセス｜問い合わせ｜Englishがウィンドウ幅を縮めると見出しに埋まる問題の修正
ウィンドウ幅が小さすぎるとフォントがエリアからはみ出してしまう問題の修正（はみ出した部分は[...]みたいにする）

**Comment by Yakan-Kettle** [comment]
アコーディオンに関しては対応完了。ウィンドウ幅の問題に関しては別のissuesで取り上げてるのでここでは扱わないことにします

**Comment by Yakan-Kettle** [comment]
・ヘッダーのアクセス｜問い合わせ｜Englishがウィンドウ幅を縮めると見出しに埋まる問題の修正
・ウィンドウ幅が小さすぎるとフォントがエリアからはみ出してしまう問題の修正（はみ出した部分は[...]みたいにする）

以上の2点が未対応です。

**Comment by ShumpeiKano** [comment]
・ヘッダーのアクセス｜問い合わせ｜Englishがウィンドウ幅を縮めると見出しに埋まる問題の修正
・ウィンドウ幅が小さすぎるとフォントがエリアからはみ出してしまう問題の修正（はみ出した部分は[...]みたいにする）
以上の2点は対応しました。
ウィンドウ幅の問題は別のissueにあるのでcloseします。
