### ISSUE TITLE
アコーディオンのあるページのスマホ対応について

### ISSUE THREAD

**Issue by Yakan-Kettle** [YngLab/Msite#54]
1.linkTextのフォントサイズが変わりません。なんでじゃ。
2.elementのwidthが多分Jsで取得しているものと思われますので、こちら側で操作できませぬ。

**Comment by Yakan-Kettle** [comment]
linkTextのフォントサイズの件はこちらの凡ミスでした。っしゃーせん。
elementのwidthに関しては対応お願いします。

**Comment by ShumpeiKano** [comment]
さだよし、widthも_tool.scssで指定してたよー
