### ISSUE TITLE
index.htmlに謎のaタグ

### ISSUE THREAD

**Issue by sKawashima** [YngLab/Msite#56]
閉じタグのないaタグが多数

**Comment by ShumpeiKano** [comment]
そんなんある？
インデント崩れちゃってて申し訳ない

**Comment by sKawashima** [comment]
たとえば156とか
インデント自動調整掛けたらドカンッって感じ

**Comment by ShumpeiKano** [comment]
ほんとだー
</a>のところを<a>で書いちゃってたみたい！
申し訳ない！
修正しました
