### ISSUE TITLE
スマホ版の「直近のイベント」についてのあれやこれや

### ISSUE THREAD

**Issue by Yakan-Kettle** [YngLab/Msite#61]
1.シングルカラム化
2.スワイプ（フリック）したときにスライドショーするように（加納のトラウマ）

**Comment by Yakan-Kettle** [comment]
2.に関しては「やめたほうがいい」とのこと。 by. hota awashima

**Comment by ShumpeiKano** [comment]
とりあえず1はできた

**Comment by ShumpeiKano** [comment]
使ってるプラグインが自動で2もやってくれてた
