### ISSUE TITLE
「直近のイベント・ワークショップ」が2段になってしまう。

### ISSUE THREAD

**Issue by ShumpeiKano** [YngLab/Msite#7]

**Comment by ShumpeiKano** [comment]
トップページにおいて画面幅を狭くすると「直近のイベント・ワークショップ」が2段になってしまう。
これは、一つ一つのコンテンツ幅は%指定なのに1pxのborderがあるからだと思われます。

**Comment by sKawashima** [comment]
コンテンツ幅をcalc(○○% - 1px）に置いたりすれば対策できそう

**Comment by ShumpeiKano** [comment]
なるほど！できそう！

**Comment by ShumpeiKano** [comment]
2段になるのが768px以下なのでcloseします
